version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
    - echo In the pre_build phase...
  build:
    commands:
    - echo Build started on `date`
  post_build:
    commands:
    - echo Build completed on `date`
    - mvn clean package
    - mv target/d-banco-conta/d-banco-conta-0.0.1-SNAPSHOT d-banco-conta-0.0.1-SNAPSHOT.jar
artifacts:
  files:
  - d-banco-conta-0.0.1-SNAPSHOT.jar
  - .ebextensions/**/*
